image: debian:stable

stages:
  - build
  - deploy

build_book:
  stage: build
  before_script:
    - apt-get update
    - apt-get install -y curl
    - curl -LO https://github.com/rust-lang-nursery/mdBook/releases/download/v${VERSION}/mdbook-v${VERSION}-x86_64-unknown-linux-gnu.tar.gz
    - tar xf mdbook-v${VERSION}-x86_64-unknown-linux-gnu.tar.gz
  script:
    - ./mdbook build
  variables:
    VERSION: "0.2.1"
  artifacts:
    paths:
      - book

pages:
  stage: deploy
  dependencies:
    - build_book
  script:
    - mv book public
  artifacts:
    paths:
      - public
